type: nn_very_large
xd_min: 0.15 # random generate xd in [xd_min, xd_max]
xd_max: 0.25
gscr_threshold: 2.5
over_value: 2.5
saving_dir: "paper_exp/sco_smart_sample_result/"
no_sample: 360               # no sample used for training
no_sample_test: 5
renewable_rescale: 1.0       # rescale the renewable generation data for larger penetration
regression: false            # if false, train NN as a classifier
smart_sample: true           # if true, use the smart sampling strategy
train_config:
  batch_size: 256
  lr: 0.001
  max_iter: 2000
  patience: 50
  weight_decay: 1e-4
active_sample: true         # if true, use the active sampling strategy
active_lr: 0.01
active_max_iter: 200 
generate_new_dataset: true
generate_new_aug: true
train_new_nn: true
optimization:  
  solver: "GUROBI"  
  option:
    MIPGap: 1e-2
    MIPGapAbs: 1e-3 
    TimeLimit: 3600
    # ConcurrentMIP: 20
    MIPFocus: 1